#!/bin/bash
# Boot the armv7 Akai MPC enviroment in QEMU w/ SDL
# Compatible with MPC 3.9.1 (Gen 1 firmware)

# Kernel and initrd are generated by a seperate script in /scripts/build_scripts/get_armv7_kernel.sh
# Make sure to run it before starting the VM or if you change the module list in the script.

# virtio-mmio.force-legacy=false is required, not optional: virtio-gpu needs
# modern virtio (VIRTIO_F_VERSION_1) and QEMU's virtio-mmio defaults to legacy,
# which leaves the GPU enumerated with no driver bound -- no /dev/dri, no
# /dev/fb0, and MPC cannot open a display.
#
# Everything is the -device (mmio) variant rather than -pci: the 32-bit virt
# machine has no PCI host bridge driver, so PCI devices are invisible. That is
# also why input is virtio-keyboard/tablet rather than usb-kbd/usb-tablet --
# the USB controllers themselves are PCI.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BUILD_DIR="$REPO_ROOT/build"

# Read the UUID off the image rather than hardcoding it: it is a property of the
# particular extraction, so it changes with every firmware version.
ROOT_UUID="$(dumpe2fs -h "$BUILD_DIR/rootfs_out.img" 2>/dev/null | awk -F': *' '/Filesystem UUID/{print $2}')"
[ -n "$ROOT_UUID" ] || { echo "ERROR: could not read a filesystem UUID from $BUILD_DIR/rootfs_out.img" >&2; exit 1; }

exec qemu-system-arm \
  -machine virt -cpu cortex-a15 -m 4096 -smp 8 \
  -global virtio-mmio.force-legacy=false \
  -device virtio-gpu-device \
  -device virtio-keyboard-device -device virtio-tablet-device \
  -kernel "$BUILD_DIR/vmlinuz-generic-armhf" \
  -initrd "$BUILD_DIR/initrd-generic-armhf" \
  -drive if=none,file=$BUILD_DIR/rootfs_out.img,format=raw,id=hd \
  -device virtio-blk-device,drive=hd \
  -drive if=none,file=$BUILD_DIR/emmc.img,format=raw,id=data \
  -device virtio-blk-device,drive=data \
  -netdev user,id=net0,hostfwd=tcp::2225-:22 -device virtio-net-pci,netdev=net0 \
  -display sdl,show-cursor=on \
  -serial mon:stdio \
  -append "root=UUID=$ROOT_UUID rw rootwait console=ttyAMA0"