#!/bin/bash
# Boot the arm64 Engine OS enviroment on macOS in QEMU w/ Cocoa 
# Compatible with both Engine 4.6.0 and 5.0.4

# Kernel and initrd are generated by a seperate script in /scripts/build_scripts/get_arm64_kernel.sh
# Make sure to run it before starting the VM or if you change the module list in the script.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BUILD_DIR="$REPO_ROOT/build"

exec qemu-system-aarch64 \
  -machine virt,highmem=on -accel hvf \
  -cpu host -m 4096 -smp 8 \
  -device virtio-gpu-pci,edid=off,xres=1280,yres=800 \
  -device usb-ehci -device qemu-xhci,id=xhci -device usb-kbd -device usb-tablet \
  -device ich9-intel-hda -device hda-duplex,audiodev=mac -audiodev coreaudio,id=mac \
  -kernel "$BUILD_DIR/vmlinuz-generic-arm64" \
  -initrd "$BUILD_DIR/initrd-generic-arm64" \
  -drive if=none,file=$BUILD_DIR/rootfs_out.img,format=raw,id=hd \
  -device virtio-blk-device,drive=hd \
  -drive if=none,file=$BUILD_DIR/data_disk.img,format=raw,id=data \
  -device virtio-blk-device,drive=data \
  -netdev user,id=net0,hostfwd=tcp::2225-:22 -device virtio-net-pci,netdev=net0 \
  -display cocoa,show-cursor=on \
  -serial mon:stdio \
  -append "root=UUID=08f20450-f04c-437b-80a8-ee64034ca4b1 rw rootwait console=ttyAMA0"