#!/bin/bash
# Boot the arm64 Engine OS enviroment on Linux in QEMU w/ GTK and virgl 
# Compatible with Engine 4.5.0+

# Kernel and initrd are generated by a seperate script in /scripts/build_scripts/get_arm64_kernel.sh
# Make sure to run it before starting the VM or if you change the module list in the script.

# Audio: hda-output (playback-only), NOT hda-duplex. Engine marks the first
# device of each enumeration pass as its default, and the capture pass runs
# second — so when a capture PCM exists it becomes the default, gets assigned
# as the input device, and the playback slot is left null. Engine then drives
# capture only and never feeds playback, which shows up as a stuck XRUN and a
# frozen "Audio_probe" watchdog rather than any error. Playback-only removes
# the ambiguity. Requires alsashim_rmz2.so preloaded into engine.service (see
# build_arm64_rootfs.sh) — without it Engine rejects the card on name alone.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BUILD_DIR="${BUILD_DIR:-$REPO_ROOT/build}"

# Overridable so scripts/qemu/run_instance.sh can point this at one instance
# directory. The defaults are the previous hardcoded values, so running this
# script directly behaves exactly as before. The kernel and initrd stay under
# BUILD_DIR: they are target-independent and shared by every instance.
ROOTFS_IMG="${ROOTFS_IMG:-$BUILD_DIR/rootfs_out.img}"
DATA_IMG="${DATA_IMG:-$BUILD_DIR/data_disk.img}"
SSH_PORT="${SSH_PORT:-2225}"
# Overridable so an instance can supply a kernel matching its rootfs: --device does
# not imply the architecture, since Engine OS and MPC each ship on both RK3288
# (armv7) and RK3588 (arm64). Defaults to the value this script used to hardcode.
KERNEL_IMG="${KERNEL_IMG:-$BUILD_DIR/vmlinuz-generic-arm64}"
INITRD_IMG="${INITRD_IMG:-$BUILD_DIR/initrd-generic-arm64}"

# Resolves QEMU_BIN plus the architecture-dependent machine, GPU, input and net
# devices from ARCH (exported by run_instance.sh). Kept in one file so the
# PCI-vs-mmio reasoning does not get copied into every launcher and drift.
# shellcheck source=arch_devices.sh
. "$(dirname "${BASH_SOURCE[0]}")/arch_devices.sh"

# virtio-gpu-gl exists only as a PCI device, and the 32-bit virt machine has no
# reachable PCI, so there is no GL path for an armhf guest at all.
[ -n "$GPU_GL_DEV" ] || {
    echo "ERROR: this launcher needs virgl, which is PCI-only, and ARCH=$ARCH has no" >&2
    echo "       usable PCI. Use the non-virgl launcher for this instance." >&2
    exit 1; }

# Read the UUID off the image rather than hardcoding it: it is a property of the
# particular extraction, so it changes with every firmware version.
ROOT_UUID="$(dumpe2fs -h "$ROOTFS_IMG" 2>/dev/null | awk -F': *' '/Filesystem UUID/{print $2}')"
[ -n "$ROOT_UUID" ] || { echo "ERROR: could not read a filesystem UUID from $ROOTFS_IMG" >&2; exit 1; }

# -accel kvm needs a host of the guest's own architecture, and `-cpu host` is
# accelerator-only: an x86_64 host can neither KVM-accelerate an aarch64 guest nor
# use that CPU model, so QEMU rejects both outright. Fall back to TCG there. On an
# arm64 Linux host these resolve to the previous hardcoded values, unchanged.
case "$(uname -m)" in
    aarch64|arm64) ACCEL="${ACCEL:-kvm}"; CPU="${CPU:-host}" ;;
    *)             ACCEL="${ACCEL:-tcg}"; CPU="${CPU:-$ARCH_CPU_DEFAULT}" ;;
esac

exec "$QEMU_BIN" \
  -machine "$MACHINE" $MMIO_GLOBAL -accel "$ACCEL" \
  -cpu "$CPU" -m 4096 -smp 8 \
  -device "$GPU_GL_DEV" \
  $INPUT_DEVS \
  $(arch_audio_devices host) -audiodev pipewire,id=host \
  -kernel "$KERNEL_IMG" \
  -initrd "$INITRD_IMG" \
  -drive if=none,file="$ROOTFS_IMG",format=raw,id=hd \
  -device virtio-blk-device,drive=hd \
  -drive if=none,file="$DATA_IMG",format=raw,id=data \
  -device virtio-blk-device,drive=data \
  -netdev user,id=net0,hostfwd=tcp::${SSH_PORT}-:22 -device "$NET_DEV",netdev=net0 \
  -display sdl,gl=on,show-cursor=on \
  -serial mon:stdio \
  -append "root=UUID=$ROOT_UUID rw rootwait console=ttyAMA0"