#!/bin/bash
# Boot the arm64 Engine OS enviroment on macOS in QEMU w/ Cocoa 
# Compatible with both Engine 4.6.0 and 5.0.4

# Kernel and initrd are generated by a seperate script in /scripts/build_scripts/get_arm64_kernel.sh
# Make sure to run it before starting the VM or if you change the module list in the script.

# Audio: hda-output (playback-only), NOT hda-duplex. Engine marks the first
# device of each enumeration pass as its default, and the capture pass runs
# second — so when a capture PCM exists it becomes the default, gets assigned
# as the input device, and the playback slot is left null. Engine then drives
# capture only and never feeds playback, which shows up as a stuck XRUN and a
# frozen "Audio_probe" watchdog rather than any error. Playback-only removes
# the ambiguity. Requires alsashim_rmz2.so preloaded into engine.service (see
# build_arm64_rootfs.sh) — without it Engine rejects the card on name alone.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BUILD_DIR="$REPO_ROOT/build"

# By default brew wont add e2fsprogs to the path
if command -v dumpe2fs &>/dev/null; then
    DUMPE2FS="dumpe2fs"
else
    DUMPE2FS="/opt/homebrew/opt/e2fsprogs/sbin/dumpe2fs"
fi

# Read the UUID off the image rather than hardcoding it: it is a property of the
# particular extraction, so it changes with every firmware version.
ROOT_UUID="$($DUMPE2FS -h "$BUILD_DIR/rootfs_out.img" 2>/dev/null | awk -F': *' '/Filesystem UUID/{print $2}')"
[ -n "$ROOT_UUID" ] || { echo "ERROR: could not read a filesystem UUID from $BUILD_DIR/rootfs_out.img" >&2; exit 1; }

exec qemu-system-aarch64 \
  -machine virt,highmem=on -accel hvf \
  -cpu host -m 4096 -smp 8 \
  -device virtio-gpu-pci,edid=off,xres=1280,yres=800 \
  -device usb-ehci -device qemu-xhci,id=xhci -device usb-kbd -device usb-tablet \
  -device ich9-intel-hda -device hda-output,audiodev=mac -audiodev coreaudio,id=mac \
  -kernel "$BUILD_DIR/vmlinuz-generic-arm64" \
  -initrd "$BUILD_DIR/initrd-generic-arm64" \
  -drive if=none,file=$BUILD_DIR/rootfs_out.img,format=raw,id=hd \
  -device virtio-blk-device,drive=hd \
  -drive if=none,file=$BUILD_DIR/data_disk.img,format=raw,id=data \
  -device virtio-blk-device,drive=data \
  -netdev user,id=net0,hostfwd=tcp::2225-:22 -device virtio-net-pci,netdev=net0 \
  -display cocoa,show-cursor=on \
  -serial mon:stdio \
  -append "root=UUID=$ROOT_UUID rw rootwait console=ttyAMA0"